
spring:
  application:
    name: myplay-member
#  profiles:
#    active: default
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: admin
#    url: jdbc:mariadb://factory-zdb-mpgdb-mariadb.factory-zdb:3306/myplayground
#    username: admin
#    password: Lxddf7pqhg
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
#  h2:
#    console:
#      enabled: true
#      path: /h2-console

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: debug
    
---
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: myplay-member
          destination: myplay
          contentType: application/json
        event-out:
          destination: myplay
          contentType: application/json